from utils.api.exceptions import CustomValidationException

CustomValidationException = CustomValidationException